import type { SupportedLanguage } from '@/app/i18n';

export interface StepData {
  mascot: string;
  titles: Record<SupportedLanguage, string>;
  descs: Record<SupportedLanguage, string>;
}

export const TOUR_STEPS: StepData[] = [
  {
    mascot: '🗺️',
    titles: {
      en: "Your Dashboard",
      tr: "Pano",
      de: "Dein Überblick",
      fr: "Ton tableau de bord",
      ar: "لوحتك",
      ja: "ダッシュボード",
      ko: "대시보드",
      'pt-BR': "Seu painel",
      'zh-Hans': "你的面板",
      id: "Dasbor Kamu",
      hi: "तुम्हारा डैशबोर्ड",
    },
    descs: {
      en: "Everything at a glance — today's progress ring, study hours, streak, and tasks waiting for you. This updates live as you complete sessions.",
      tr: "Her şey tek bakışta — bugünkü ilerleme halkası, çalışma saatleri, seri ve seni bekleyen görevler. Oturumları tamamladıkça canlı güncellenir.",
      de: "Alles auf einen Blick — Tagesfortschrittsring, Lernstunden, Serie und wartende Aufgaben. Aktualisiert sich live nach jeder Sitzung.",
      fr: "Tout d'un coup d'œil — anneau de progression, heures d'étude, série et tâches qui t'attendent. Se met à jour en direct après chaque session.",
      ar: "كل شيء دفعة واحدة — حلقة التقدم اليومي، ساعات الدراسة، السلسلة والمهام بانتظارك. يتحدث لحظياً مع كل جلسة.",
      ja: "一目で全部わかる — 今日の進捗リング、学習時間、連続記録、待機中のタスク。セッション完了のたびにリアルタイム更新。",
      ko: "한눈에 모두 파악 — 오늘의 진행 링, 학습 시간, 스트릭, 대기 중인 과제. 세션 완료 시 실시간 업데이트.",
      'pt-BR': "Tudo de relance — anel de progresso, horas de estudo, sequência e tarefas esperando. Atualiza em tempo real a cada sessão.",
      'zh-Hans': "一览无余 — 今日进度环、学习时间、连胜和待完成任务。每次学习后实时更新。",
      id: "Semua dalam sekejap — cincin kemajuan hari ini, jam belajar, streak, dan tugas yang menunggu. Diperbarui langsung setiap sesi selesai.",
      hi: "एक नज़र में सब कुछ — आज का प्रोग्रेस रिंग, पढ़ाई के घंटे, स्ट्रीक और प्रतीक्षारत टास्क। हर सेशन के बाद लाइव अपडेट।",
    },
  },
  {
    mascot: '▶️',
    titles: {
      en: "Start a Session",
      tr: "Oturum Başlat",
      de: "Sitzung starten",
      fr: "Démarrer une session",
      ar: "ابدأ جلسة",
      ja: "セッションを開始",
      ko: "세션 시작",
      'pt-BR': "Iniciar uma sessão",
      'zh-Hans': "开始学习",
      id: "Mulai Sesi",
      hi: "सेशन शुरू करें",
    },
    descs: {
      en: "Tap the play button on any task. Set a duration, focus — lofi music plays in the background. Done? It logs automatically and your plan updates.",
      tr: "Herhangi bir görevin oynat butonuna dokun. Süre seç, odaklan — arka planda lofi müzik çalar. Bitti mi? Otomatik kaydedilir ve plan güncellenir.",
      de: "Tippe den Play-Button einer Aufgabe. Dauer einstellen, fokussieren — Lofi-Musik spielt im Hintergrund. Fertig? Wird automatisch gespeichert, Plan aktualisiert.",
      fr: "Appuie sur le bouton lecture d'une tâche. Règle la durée, concentre-toi — musique lofi en fond. Terminé ? Enregistrement auto, plan mis à jour.",
      ar: "اضغط على زر التشغيل لأي مهمة. اضبط المدة، ركّز — موسيقى لوفاي في الخلفية. انتهيت؟ تُسجَّل تلقائياً وتُحدَّث الخطة.",
      ja: "タスクの再生ボタンをタップ。時間を設定して集中 — バックグラウンドでLofi音楽が流れる。完了したら自動記録、プランも更新される。",
      ko: "과제의 재생 버튼을 탭. 시간 설정 후 집중 — 배경에서 로파이 음악 재생. 완료되면 자동 저장, 플랜도 업데이트.",
      'pt-BR': "Toque no botão de play de uma tarefa. Defina a duração, foque — música lofi toca em segundo plano. Concluído? Salvo automaticamente, plano atualizado.",
      'zh-Hans': "点击任务的播放按钮。设置时长，专注学习 — 后台播放 Lofi 音乐。完成后自动记录，计划同步更新。",
      id: "Ketuk tombol play pada tugas. Atur durasi, fokus — musik lofi di latar belakang. Selesai? Tersimpan otomatis, rencana diperbarui.",
      hi: "किसी टास्क का प्ले बटन टैप करें। अवधि सेट करें, फोकस करें — पृष्ठभूमि में लोफाई संगीत बजेगा। हो गया? अपने आप सेव होगा, प्लान अपडेट होगा।",
    },
  },
  {
    mascot: '📅',
    titles: {
      en: "Calendar",
      tr: "Takvim",
      de: "Kalender",
      fr: "Calendrier",
      ar: "التقويم",
      ja: "カレンダー",
      ko: "캘린더",
      'pt-BR': "Calendário",
      'zh-Hans': "日历",
      id: "Kalender",
      hi: "कैलेंडर",
    },
    descs: {
      en: "Every study day, mapped out. Tap any date to see what's planned — past, present, future, all in one place.",
      tr: "Tüm çalışma günlerin haritada. Bir tarihe dokun ve o güne ait planı gör — geçmiş, bugün, gelecek.",
      de: "Alle Lerntage auf einen Blick. Tippe auf ein Datum, um den Plan zu sehen — Vergangenheit, Gegenwart, Zukunft.",
      fr: "Chaque jour d'étude, cartographié. Appuie sur une date pour voir le plan — passé, présent, futur.",
      ar: "كل يوم دراسة على الخريطة. اضغط على أي تاريخ لرؤية الخطة — الماضي والحاضر والمستقبل.",
      ja: "全学習日がマッピングされています。日付をタップしてプランを確認 — 過去・現在・未来すべて一目で。",
      ko: "모든 학습일이 매핑됩니다. 날짜를 탭해서 계획 확인 — 과거, 현재, 미래 모두 한 눈에.",
      'pt-BR': "Cada dia de estudo, mapeado. Toque em uma data para ver o plano — passado, presente, futuro.",
      'zh-Hans': "每一天学习都有安排。点击任意日期查看计划 — 过去、现在、未来一览无遗。",
      id: "Setiap hari belajar terpetakan. Ketuk tanggal untuk melihat rencana — masa lalu, kini, masa depan.",
      hi: "हर पढ़ाई का दिन मैप पर। किसी तारीख को टैप करें — पिछला, आज, आने वाला, सब एक जगह।",
    },
  },
  {
    mascot: '🏆',
    titles: {
      en: "Progress",
      tr: "İlerleme",
      de: "Fortschritt",
      fr: "Progression",
      ar: "التقدم",
      ja: "進捗",
      ko: "진행",
      'pt-BR': "Progresso",
      'zh-Hans': "进度",
      id: "Kemajuan",
      hi: "प्रगति",
    },
    descs: {
      en: "Study hours, sessions, badges — it's all tracked here. Every day you show up, the streak grows. Miss one, it resets.",
      tr: "Çalışma saatleri, oturumlar, rozetler — hepsi burada izlenir. Her gün gelirsen seri uzar. Bir gün kaçırırsan sıfırlanır.",
      de: "Stunden, Sitzungen, Abzeichen — alles wird hier erfasst. Jeden Tag mehr Serie. Einen Tag verpassen, Reset.",
      fr: "Heures, sessions, badges — tout est suivi ici. Chaque jour que tu te montres, la série grandit. Rate un jour, elle repart de zéro.",
      ar: "الساعات والجلسات والشارات — كلها مُتتبَّعة هنا. كل يوم تظهر فيه، السلسلة تطول. فوّت يوماً، تعود للصفر.",
      ja: "学習時間、セッション、バッジ — すべてここで追跡。毎日続けるほど連続記録が伸びる。一日でも休むとリセット。",
      ko: "학습 시간, 세션, 배지 — 모두 여기서 추적. 매일 나타날수록 스트릭이 늘어난다. 하루 빠지면 리셋.",
      'pt-BR': "Horas, sessões, distintivos — tudo rastreado aqui. Cada dia que você aparece, a sequência cresce. Perca um dia, recomeça do zero.",
      'zh-Hans': "学习时间、课程、徽章 — 全在这里追踪。每天坚持，连胜就增长。缺一天，重置。",
      id: "Jam, sesi, lencana — semua dilacak di sini. Setiap hari hadir, streak bertambah. Lewatkan satu hari, reset.",
      hi: "घंटे, सेशन, बैज — सब यहाँ ट्रैक होता है। हर दिन पढ़ोगे, स्ट्रीक बढ़ेगी। एक दिन चूके, रिसेट।",
    },
  },
  {
    mascot: '⚡️',
    titles: {
      en: "Profile",
      tr: "Profil",
      de: "Profil",
      fr: "Profil",
      ar: "الملف الشخصي",
      ja: "プロフィール",
      ko: "프로필",
      'pt-BR': "Perfil",
      'zh-Hans': "我的",
      id: "Profil",
      hi: "प्रोफाइल",
    },
    descs: {
      en: "Exam countdown, weekly load, all your settings. Change your goal or intensity anytime — the plan rebuilds in seconds.",
      tr: "Sınav geri sayımı, haftalık yük, tüm ayarların. Hedef veya yoğunluk değiştir — plan saniyeler içinde yeniden oluşur.",
      de: "Prüfungs-Countdown, Wochenlast, alle Einstellungen. Ziel oder Intensität jederzeit ändern — der Plan wird in Sekunden neu erstellt.",
      fr: "Compte à rebours, charge hebdo, tous tes réglages. Change ton objectif ou ton intensité — le plan se reconstruit en secondes.",
      ar: "العد التنازلي والحمل الأسبوعي وكل إعداداتك. غيّر هدفك أو كثافتك في أي وقت — تُعاد الخطة في ثوانٍ.",
      ja: "試験カウントダウン、週間負荷、すべての設定。いつでも目標や強度を変更できる — プランは数秒で再構築されます。",
      ko: "시험 카운트다운, 주간 부하, 모든 설정. 언제든 목표나 강도 변경 — 플랜은 몇 초 만에 재구성됩니다.",
      'pt-BR': "Contagem regressiva, carga semanal, todas as configurações. Mude seu objetivo ou intensidade — o plano se reconstrói em segundos.",
      'zh-Hans': "考试倒计时、每周负荷、所有设置。随时更改目标或强度 — 计划在几秒内重建。",
      id: "Hitung mundur ujian, beban mingguan, semua pengaturan. Ubah tujuan atau intensitas kapan saja — rencana dibangun ulang dalam hitungan detik.",
      hi: "परीक्षा काउंटडाउन, साप्ताहिक लोड, सारी सेटिंग्स। कभी भी लक्ष्य या तीव्रता बदलो — प्लान सेकंडों में फिर से बनता है।",
    },
  },
];

export const SKIP_LABELS: Record<SupportedLanguage, string> = {
  en: 'Skip', tr: 'Geç', de: 'Überspringen', fr: 'Passer', ar: 'تخطي',
  ja: 'スキップ', ko: '건너뛰기', 'pt-BR': 'Pular', 'zh-Hans': '跳过', id: 'Lewati', hi: 'छोड़ें',
};
export const NEXT_LABELS: Record<SupportedLanguage, string> = {
  en: 'Got it →', tr: 'Anladım →', de: 'Verstanden →', fr: 'Compris →', ar: 'فهمت ←',
  ja: '了解 →', ko: '알겠어요 →', 'pt-BR': 'Entendi →', 'zh-Hans': '明白了 →', id: 'Mengerti →', hi: 'समझ गया →',
};
export const DONE_LABELS: Record<SupportedLanguage, string> = {
  en: "Let's go!", tr: 'Hadi başla!', de: "Los geht's!", fr: "C'est parti!", ar: '!هيا نبدأ',
  ja: 'さあ始めよう！', ko: '시작하자!', 'pt-BR': 'Vamos lá!', 'zh-Hans': '出发！', id: 'Ayo mulai!', hi: 'चलो शुरू करें!',
};
